### ISSUE TITLE
Line 7

### ISSUE THREAD

**Issue by ncopz** [Nathi72TcF/Gweva-Shopping-Site#1]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\shop\db.php:7 Stack trace: #0 C:\xampp\htdocs\shop\include\home\header.php(1): include() #1 C:\xampp\htdocs\shop\index.php(1): include('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\shop\db.php on line 7

**Comment by Nathi72TcF** [comment]
I used xammp and it works fine on my side
